[package]
name = "multigraphrs"
version = "0.1.2"
edition = "2024"
authors = ["Șoiman Vasile-Cristian <vasilecristiansoiman@gmail.com>"]
description = "A versatile, strategy-pattern based MultiGraph library supporting directed, undirected, and weighted graphs."
license = "MIT"
repository = "https://github.com/SoimanVasile/multigraphrs"
keywords = ["graph", "multigraph", "directed", "undirected", "weighted"]
categories = ["data-structures", "algorithms"]
readme = "README.md"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
memmap2 = "0.9.10"
ahash = "0.8.11"
arc-swap = "1.9.2"

[profile.profiling]
inherits = "release"
debug = true

[dev-dependencies]
tempfile = "3"

[lints.clippy]
pedantic = {level = "deny", priority = -1}
nursery = { level = "deny", priority = -1}
unwrap_used = "deny"
expected_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_suctraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
